version: '3'
volumes:
  postgres_data:
    driver: 'local'
services:
  postgres:
    build:
      context: ./misc
      dockerfile: Dockerfile
    container_name: "postgres_db"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "your DB name" # todo: need custom
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - ./misc/data:/var/lib/postgresql/data
      - ./misc/sql:/docker-entrypoint-initdb.d